#!/usr/bin/env python3

import argparse
import libwyag
import sys



argparser = argparse.ArgumentParser(description="The studpid content tracker")

argsubparsers = argparser.add_subparsers(title="Commands", dest="command")
argsubparsers.required = True

argsp = argsubparsers.add_parser("init", help="Initilize a new, empty repository.")

argsp.add_argument("path",
                    metavar="directory",
                    nargs="?",
                    default=".",
                    help="Where to create the repository.")



def cmd_init(args):
    libwyag.repo_create(args.path)



def main(argv=sys.argv[1:]):
    args = argparser.parse_args(argv)

    if args.command == "init"       : cmd_init(args)
    else :
        print("No command specified")
        return -1


main()
